# -*- coding: utf-8 -*-
"""
/***************************************************************************
 layerSourceChecker
                                 A QGIS plugin
 It will check if the layer's source is or not in a specific folder
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-18
        copyright            : (C) 2019 by Marcelo Baliu Fimaneghi
        email                : ma.baliu@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load layerSourceChecker class from file layerSourceChecker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .check_source import layerSourceChecker
    return layerSourceChecker(iface)
